### ISSUE TITLE
Addon install is not clean and lead to conflicts

### ISSUE THREAD

**Issue by Klaim** [Manonox/godot-proto-csgs#1]
![image](https://github.com/user-attachments/assets/8609835e-94ca-4d84-9b0b-ceca61bfb4a3)

This is what current addon install looks like for Godot 4.3-rc1
You can see many issues here, including directories (skybox/) and files (demo.tscn, git files, project.godot) that should not be part of the install.

I dont know how godot addon install works but if there is a way to ignore everything but the addons/proto-csgs/ directory, that would work. I would also suggest to put a copy of the licence in that directory.

Hope it helps 👍🏽

**Comment by handras** [comment]
Same in Godot 4.2-stable, ofc

**Comment by Manonox** [comment]
Yeah, I still have no idea how to set it up nicer than this, probably should just put the whole addon into `addons/`, which is not cool :(

**Comment by Klaim** [comment]
Maybe look at some other well behaved add-ons? See how they do it. Ones that have demo scenes, to be close to this one?

**Comment by Manonox** [comment]
> Maybe look at some other well behaved add-ons? See how they do it. Ones that have demo scenes, to be close to this one?

My other addon installs nicely, but you still have to turn off things
I want only the addon to be installed by default, which is kinda? impossible with the way asset library works right now. (or have 2 repositories, which is meh)
Currently just trying to change the file structure to the way it it in https://github.com/Manonox/DevBlocks

**Comment by Manonox** [comment]
Fixed with https://github.com/Manonox/godot-proto-csgs/commit/14f15e0369b479e445545d8a74ec2911403d1d92
