### ISSUE TITLE
Textures not applied at runtime

### ISSUE THREAD

**Issue by handras** [Manonox/godot-proto-csgs#2]
I tried changing the texture of a box which is reflected in the editor, but not during runtime.
Instructions are unclear how to change the color.
![kép](https://github.com/user-attachments/assets/3b5b41aa-6ff1-4fc9-8287-a6772e09b813)
![kép](https://github.com/user-attachments/assets/c001585c-d002-449a-bde2-5b053d2a6f1f)

**Comment by Manonox** [comment]
You should change the export values instead, they set the material up for you
![image](https://github.com/user-attachments/assets/995de60c-eb97-4b38-9da7-2e6d8d0ae8d3)

**Comment by Manonox** [comment]
Can probably add the ability to override the material manually

**Comment by Manonox** [comment]
I disabled the material update on _ready in the editor and when running the game, still have no idea why it was there in the first place
Fixed with https://github.com/Manonox/godot-proto-csgs/commit/7314ecb0c9655ade0e1bb064b39978599e1e4d3e

**Comment by handras** [comment]
Thank you! I can't understand how I missed the properties. Allowing material override is good for custom materials as well.
